import { LegalPage } from "@/components/landing/LegalPage";

export default function Terms() {
  return (
    <LegalPage
      title="Terms of service"
      updated="September 3, 2026"
      intro="These terms govern your use of SMEs Agent. By creating an account or using the service, you agree to them."
      sections={[
        {
          heading: "The service",
          paragraphs: [
            "SMEs Agent is an automation platform that plans and executes business workflows. The agent proposes a structured plan before anything runs, and execution only happens after your approval.",
          ],
        },
        {
          heading: "Accounts",
          paragraphs: [
            "Provide accurate information when creating an account and keep your credentials secure. If you use the service on behalf of an organization, you confirm you have authority to bind it to these terms. Notify us immediately of any unauthorized access.",
          ],
        },
        {
          heading: "Acceptable use",
          bullets: [
            "Do not use the service for unlawful, infringing, or harmful activity.",
            "Do not attempt to disrupt, overload, or gain unauthorized access to the service.",
            "Do not resell or redistribute the service without a separate agreement.",
            "Respect the usage limits of your plan.",
          ],
        },
        {
          heading: "Plans and billing",
          paragraphs: [
            "Paid plans are billed monthly in advance and renew automatically until cancelled. You can cancel anytime from your account settings; cancellation takes effect at the end of the current billing period. Fees are non-refundable except where required by law.",
          ],
        },
        {
          heading: "AI output and approvals",
          paragraphs: [
            "Agent output is generated by AI and may contain errors or omissions. You are responsible for reviewing plans before approving execution and for decisions you make based on the output. Nothing in the service constitutes professional, legal, or financial advice.",
          ],
        },
        {
          heading: "Your content",
          paragraphs: [
            "You retain ownership of the data and content you submit. You grant us a limited license to process it solely to operate and provide the service.",
          ],
        },
        {
          heading: "Intellectual property",
          paragraphs: [
            "The service, including its software, design, and branding, is owned by SMEs Agent and protected by applicable laws. These terms grant you no rights in the service except the right to use it.",
          ],
        },
        {
          heading: "Disclaimers and liability",
          paragraphs: [
            "The service is provided \"as is\" without warranties of any kind, except as stated in these terms or required by law. To the maximum extent permitted by law, SMEs Agent is not liable for indirect, incidental, or consequential damages, and our total liability is limited to the fees you paid in the 12 months before the claim.",
          ],
        },
        {
          heading: "Termination",
          paragraphs: [
            "You may stop using the service and delete your account at any time. We may suspend or terminate accounts that violate these terms or create risk for other users, with notice where practicable.",
          ],
        },
        {
          heading: "Changes to these terms",
          paragraphs: [
            "We may update these terms as the product evolves. For material changes, we will notify you in advance through the service or by email. Continued use after the effective date constitutes acceptance.",
          ],
        },
        {
          heading: "Contact",
          paragraphs: ["Questions about these terms? Email support@xer0bit.com."],
        },
      ]}
    />
  );
}
