import { ECG } from '../ecg-config';
const SERVER = ECG.proxyUrl.replace(/\/$/, '');
const PROJECT_ID = ECG.projectId;

function accessHeaders(): Record<string, string> {
  const token = localStorage.getItem(`ecg_access_${PROJECT_ID}`);
  return token ? { 'x-dashboard-access': token } : {};
}

async function req(method: string, path: string, body?: unknown) {
  const sep = path.includes('?') ? '&' : '?';
  const url = `${SERVER}/api/v1/ecg-proxy${path}${sep}projectId=${PROJECT_ID}`;
  const res = await fetch(url, {
    method,
    credentials: 'include',
    headers: { 'Content-Type': 'application/json', ...accessHeaders() },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const e = await res.json().catch(() => ({}));
    throw new Error((e as { error?: string }).error || `API error ${res.status}`);
  }
  return res.json();
}

async function reqMultipart(path: string, formData: FormData) {
  const sep = path.includes('?') ? '&' : '?';
  const url = `${SERVER}/api/v1/ecg-proxy${path}${sep}projectId=${PROJECT_ID}`;
  const res = await fetch(url, {
    method: 'POST',
    credentials: 'include',
    headers: { ...accessHeaders() },
    body: formData,
  });
  if (!res.ok) {
    const e = await res.json().catch(() => ({}));
    throw new Error((e as { error?: string }).error || `API error ${res.status}`);
  }
  return res.json();
}

export async function chat(messages: { role: string; content: string }[]) {
  const url = `${SERVER}/api/v1/ecg-chat?projectId=${PROJECT_ID}`;
  const res = await fetch(url, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json', ...accessHeaders() },
    body: JSON.stringify({ messages }),
  });
  if (!res.ok) {
    const e = await res.json().catch(() => ({}));
    throw new Error((e as { error?: string }).error || `Chat error ${res.status}`);
  }
  return res.json() as Promise<{ reply: string; actions: { tool: string; result: unknown }[] }>;
}

export const ecgApi = {
  // Agent templates
  templates:  { list: () => req('GET', '/agent-templates') },

  // Agents
  agents: {
    list:    () => req('GET', '/agents'),
    get:     (id: string) => req('GET', `/agents/${id}`),
    create:  (data: unknown) => req('POST', '/agents', data),
    update:  (id: string, data: unknown) => req('PATCH', `/agents/${id}`, data),
    delete:  (id: string) => req('DELETE', `/agents/${id}`),
    run:     (id: string) => req('POST', `/agents/${id}/run`),
  },

  // Schedulers
  schedulers: {
    list:    () => req('GET', '/schedulers'),
    create:  (data: unknown) => req('POST', '/schedulers', data),
    update:  (id: string, data: unknown) => req('PATCH', `/schedulers/${id}`, data),
    delete:  (id: string) => req('DELETE', `/schedulers/${id}`),
    // Backend route is /replan, not /trigger   there is no /trigger endpoint.
    trigger: (id: string) => req('POST', `/schedulers/${id}/replan`),
  },

  // Planned posts
  posts: {
    list:    () => req('GET', '/planned-posts'),
    create:  (data: unknown) => req('POST', '/planned-posts', data),
    delete:  (id: string) => req('DELETE', `/planned-posts/${id}`),
    approve: (id: string) => req('PATCH', `/planned-posts/${id}`, { status: 'approved' }),
    reject:  (id: string) => req('PATCH', `/planned-posts/${id}`, { status: 'rejected' }),
  },

  // Post visuals   Canva-style canvas (background + positioned text/image/
  // shape objects), generated by the agent and directly editable. See
  // VisualEditorPage.
  visualPosts: {
    list:       (plannedPostId?: string) => req('GET', plannedPostId ? `/visual-posts?plannedPostId=${plannedPostId}` : '/visual-posts'),
    get:        (id: string) => req('GET', `/visual-posts/${id}`),
    generate:   (data: { agentId?: string; plannedPostId?: string; postContent: string; platform?: string; stylePrompt?: string }) =>
      req('POST', '/visual-posts/generate', data),
    update:     (id: string, data: { objects?: unknown[]; background?: string }) => req('PATCH', `/visual-posts/${id}`, data),
    regenerate: (id: string, data: { postContent: string; stylePrompt?: string }) => req('POST', `/visual-posts/${id}/regenerate`, data),
    finalize:   (id: string) => req('POST', `/visual-posts/${id}/finalize`),
  },

  // Connectors   the backend router (connectors.ts) is mounted directly at
  // /v1/ecg/connectors but its actual routes all live under /org (/org,
  // /org/:id, /org/:id/test, /zapier/discover)   there is no bare `/` or
  // `/:id` route. Every call here used to 404 silently before this fix.
  connectors: {
    list:    () => req('GET', '/connectors/org'),
    create:  (data: unknown) => req('POST', '/connectors/org', data),
    update:  (id: string, data: unknown) => req('PATCH', `/connectors/org/${id}`, data),
    delete:  (id: string) => req('DELETE', `/connectors/org/${id}`),
    test:    (id: string) => req('POST', `/connectors/org/${id}/test`),
  },

  // Runs
  runs: { list: () => req('GET', '/runs') },

  // Knowledge
  knowledge: {
    list:   () => req('GET', '/knowledge'),
    upload: (formData: FormData) => reqMultipart('/knowledge/upload', formData),
    delete: (id: string) => req('DELETE', `/knowledge/${id}`),
  },

  // Knowledge bases
  knowledgeBases: {
    list:    () => req('GET', '/knowledge-bases'),
    create:  (data: unknown) => req('POST', '/knowledge-bases', data),
    update:  (id: string, data: unknown) => req('PATCH', `/knowledge-bases/${id}`, data),
    delete:  (id: string) => req('DELETE', `/knowledge-bases/${id}`),
  },

  // Org settings
  org: {
    get:    () => req('GET', '/org'),
    update: (data: unknown) => req('PATCH', '/org', data),
  },

  // Team
  team: {
    list:    () => req('GET', '/team'),
    create:  (data: unknown) => req('POST', '/team', data),
    delete:  (id: string) => req('DELETE', `/team/${id}`),
  },

  // API keys
  apiKeys: {
    list:   () => req('GET', '/api-keys'),
    create: (data: unknown) => req('POST', '/api-keys', data),
    revoke: (id: string) => req('PATCH', `/api-keys/${id}/revoke`),
  },

  // Billing
  billing: {
    invoices: () => req('GET', '/billing/invoices'),
  },

  // Summary
  summary: { get: () => req('GET', '/summary') },
};
