const fs = require('fs');
const path = require('path');
const { getViteApi } = require('./viteApi');
const { activeServers } = require('./previewState');

function getEsbuildLoader(filePath) {
    const ext = path.extname(filePath).toLowerCase();
    switch (ext) {
        case '.tsx': return 'tsx';
        case '.ts': return 'ts';
        case '.jsx': return 'jsx';
        case '.js': return 'js';
        case '.mjs': return 'js';
        case '.mts': return 'ts';
        case '.cts': return 'ts';
        case '.json': return 'json';
        default: return null;
    }
}

function formatValidationError(filePath, error) {
    const message = error?.message || 'Invalid source file';
    const location = error?.location;
    const line = location?.line;
    const column = location?.column != null ? location.column + 1 : undefined;
    const lineText = location?.lineText || '';
    const prefix = line && column
        ? `${filePath}:${line}:${column}`
        : filePath;

    return {
        file: filePath,
        line,
        column,
        message,
        lineText,
        summary: `${prefix} ${message}`.trim(),
    };
}

// System/config files generated by initProject() — skip validation entirely.
// Vite reads these in-memory (configFile: false) so on-disk content is irrelevant.
const SKIP_VALIDATION_FILES = new Set([
    'postcss.config.js', 'postcss.config.cjs', 'postcss.config.mjs',
    'tailwind.config.js', 'tailwind.config.ts', 'tailwind.config.cjs',
    'vite.config.ts', 'vite.config.js',
    'tsconfig.json', 'tsconfig.node.json',
    'components.json',
]);

async function validateSourceFile(filePath, content) {
    const basename = path.basename(filePath);
    if (SKIP_VALIDATION_FILES.has(basename)) return [];

    // Ambient declaration files (vite-env.d.ts, etc.) carry no runtime code,
    // only type declarations   there's nothing to transpile/emit. Feeding one
    // to ts.transpileModule() throws TypeScript's internal
    // "Debug Failure. Output generation failed" (the emitter asserts against
    // producing JS output for a file it detects as declaration-only via the
    // .d.ts filename suffix). That crash was being recorded as a real build
    // error, permanently marking every project unhealthy the moment its
    // (perfectly valid, untouched) vite-env.d.ts got validated.
    if (filePath.endsWith('.d.ts')) return [];

    const loader = getEsbuildLoader(filePath);
    if (!loader) return [];

    const isScriptLike = ['tsx', 'ts', 'jsx', 'js', 'mjs', 'mts', 'cts'].includes(loader);
    if (isScriptLike) {
        try {
            const ts = require('typescript');
            const result = ts.transpileModule(content, {
                compilerOptions: {
                    target: ts.ScriptTarget.ES2020,
                    module: ts.ModuleKind.ESNext,
                    jsx: ts.JsxEmit.ReactJSX,
                },
                fileName: filePath,
                reportDiagnostics: true,
            });

            const diagnostics = Array.isArray(result.diagnostics) ? result.diagnostics : [];
            const hardErrors = diagnostics.filter((d) => d.category === ts.DiagnosticCategory.Error);
            if (hardErrors.length === 0) {
                // TypeScript passed — also run esbuild transform so errors like
                // `unexpected "{"` (JSX shorthand `<Comp {prop}>`) are caught before
                // the file is written to disk. These errors only appear at Vite
                // transform time and are NOT reported by TypeScript's transpileModule.
                if (loader === 'tsx' || loader === 'jsx') {
                    try {
                        const { transformWithEsbuild } = await getViteApi();
                        await transformWithEsbuild(content, filePath, {
                            loader,
                            jsx: 'automatic',
                            sourcemap: false,
                        });
                    } catch (esbuildErr) {
                        // TypeScript accepted the file — esbuild disagreement is
                        // non-fatal.  Let Vite HMR surface it as a browser overlay
                        // instead of hard-rejecting the entire update with 422.
                        const hint = esbuildErr?.errors?.[0]?.text || esbuildErr?.message || '';
                        console.warn(`[Validate] esbuild warning (TS passed): ${filePath} — ${hint}`);
                    }
                }
                return [];
            }

            return hardErrors.map((diag) => {
                const message = ts.flattenDiagnosticMessageText(diag.messageText, '\n') || 'Invalid source file';
                if (!diag.file || typeof diag.start !== 'number') {
                    return {
                        file: filePath,
                        line: undefined,
                        column: undefined,
                        message,
                        lineText: '',
                        summary: `${filePath} ${message}`.trim(),
                    };
                }

                const lineAndChar = diag.file.getLineAndCharacterOfPosition(diag.start);
                const line = lineAndChar.line + 1;
                const column = lineAndChar.character + 1;
                const lineText = diag.file.text.split('\n')[line - 1] || '';

                return {
                    file: filePath,
                    line,
                    column,
                    message,
                    lineText,
                    summary: `${filePath}:${line}:${column} ${message}`.trim(),
                };
            });
        } catch (error) {
            return [formatValidationError(filePath, error)];
        }
    }

    try {
        const { transformWithEsbuild } = await getViteApi();
        await transformWithEsbuild(content, filePath, {
            loader,
            jsx: 'automatic',
            sourcemap: false,
        });
        return [];
    } catch (error) {
        if (Array.isArray(error?.errors) && error.errors.length > 0) {
            return error.errors.map((entry) => formatValidationError(filePath, entry));
        }

        return [formatValidationError(filePath, error)];
    }
}

function buildValidationResponse(errors) {
    const items = errors.map((error) => {
        const location = error.line && error.column ? `:${error.line}:${error.column}` : '';
        const codeLine = error.lineText ? `\n${error.lineText}` : '';
        return `${error.file}${location} ${error.message}${codeLine}`;
    });

    return {
        error: `Preview validation failed:\n${items.join('\n\n')}`,
        validationErrors: errors,
    };
}

function repairMalformedDefaultStringParams(content) {
    let next = content;
    // Handles patterns like: suffix = ', prefix = ''
    next = next.replace(/(\b[a-zA-Z_$][\w$]*\s*=\s*)'(?=\s*,\s*[a-zA-Z_$][\w$]*\s*=)/g, "$1''");
    next = next.replace(/(\b[a-zA-Z_$][\w$]*\s*=\s*)"(?=\s*,\s*[a-zA-Z_$][\w$]*\s*=)/g, '$1""');
    return next;
}

// ── Stable Architecture: Cross-file import resolution check ───────────────────
// Validates that all relative imports resolve to files that WILL exist after
// the update. This catches "Module not found" errors BEFORE writing to disk,
// which is the #1 cause of broken previews.
function checkCrossFileImports(projectRoot, requestFiles, fullSync) {
    const virtualFS = new Set();

    // 1. Include existing files on disk (unless fullSync replaces everything)
    if (!fullSync) {
        const walkDisk = (dir) => {
            let entries;
            try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
            for (const entry of entries) {
                if (['node_modules', '.vite-cache', '.git', '.cache', '.src-snapshot'].includes(entry.name)) continue;
                const abs = path.join(dir, entry.name);
                if (entry.isDirectory()) walkDisk(abs);
                else virtualFS.add(path.relative(projectRoot, abs).replace(/\\/g, '/'));
            }
        };
        walkDisk(projectRoot);
    }

    // 2. Overlay request files (they are the new source of truth for these paths)
    const requestFileMap = new Map();
    for (const file of requestFiles) {
        const safePath = file.path.replace(/^\/+/, '');
        virtualFS.add(safePath);
        requestFileMap.set(safePath, file.content || '');
    }

    // 3. Check relative imports in all script files
    const errors = [];
    const scriptExts = /\.(tsx?|jsx?)$/;
    const scriptFiles = [...virtualFS].filter((p) => scriptExts.test(p));

    for (const filePath of scriptFiles) {
        let content = requestFileMap.get(filePath);
        if (content === undefined) {
            try { content = fs.readFileSync(path.join(projectRoot, filePath), 'utf-8'); }
            catch { continue; }
        }
        if (!content || typeof content !== 'string') continue;

        // Skip binary-encoded files
        if (content.startsWith('__SMEsAgent_BIN64__')) continue;

        // Extract relative imports (starting with ./ or ../)
        const importRegex = /(?:import\s+(?:[\w{}\s*,]+\s+from\s+)?|require\s*\(\s*|export\s+(?:[\w{}\s*,]+\s+from\s+)?)['"](\.[^'"]+)['"]/g;
        let match;
        while ((match = importRegex.exec(content)) !== null) {
            const importPath = match[1];
            // Skip CSS/SCSS/asset imports (these are handled by Vite)
            if (/\.(css|scss|sass|less|svg|png|jpg|jpeg|gif|webp|ico|woff2?|ttf|eot|mp4|webm)$/.test(importPath)) continue;

            const fileDir = path.dirname(filePath);
            const resolved = path.posix.normalize(path.posix.join(fileDir, importPath));

            // Check all possible resolution paths
            const candidates = [
                resolved,
                resolved + '.tsx',
                resolved + '.ts',
                resolved + '.jsx',
                resolved + '.js',
                resolved + '/index.tsx',
                resolved + '/index.ts',
                resolved + '/index.jsx',
                resolved + '/index.js',
            ];

            if (!candidates.some((c) => virtualFS.has(c))) {
                errors.push({
                    file: filePath,
                    message: `Unresolved local import '${importPath}' — no matching file found`,
                    summary: `${filePath}: Unresolved import '${importPath}'`,
                });
            }
        }
    }

    return errors;
}

// ── Stable Architecture: Post-write Vite transform check ─────────────────────
// After files are written, attempt to load the entry point through Vite's
// module graph. If it fails to transform, the project is broken.
//
// changedPaths (optional): relative paths this push actually wrote. A file
// that isn't touched by the push can't have just become broken -- it either
// passed this same check on a prior push or was scaffolded from a known-good
// template -- so a partial push only needs to re-check what it wrote instead
// of every script file in the project. Without this, a 1-file repair-loop
// push on a 300-file project paid for transforming all 300 on the blocking
// response path, which is what turned into request timeouts ("Something
// needs fixing") on larger projects. Omit changedPaths (or pass a fullSync
// push's own file list, which already covers ~the whole tree) to fall back
// to the full walk.
/**
 * Whether a project-relative path is app source this check should parse.
 *
 * `__edge_functions__/*.js` mirrors are raw sandbox bodies: bare top-level
 * statements, a top-level `return`, free `params`/`secrets`/`db` names. They
 * are never bundled or served (see viteConfig.js and materializeProjectFiles,
 * which both already skip the directory). Running esbuild over one produced a
 * page of syntax errors for a file the app never loads, the push was rolled
 * back, and the agent's only change that run was reverted with a "failed to
 * build" notice (CardPro, 2026-09-02 10:41 UTC).
 */
function isBuildCheckable(relPath) {
    const normalized = String(relPath || '').replace(/\\/g, '/').replace(/^\/+/, '');
    if (normalized.startsWith('__edge_functions__/')) return false;
    return /\.(tsx|jsx|ts|js)$/.test(normalized);
}

async function quickViteBuildCheck(projectId, projectRoot, changedPaths) {
    const instance = activeServers.get(projectId);
    // Guard is on instance existence only, not `.vite`   this check never
    // touches instance.vite (it only needs getViteApi()'s transformWithEsbuild
    // below), and a child-process instance ({proc, port}) has no `.vite` field
    // at all despite being just as real/running as a legacy in-process one.
    if (!instance) return { ok: true, errors: [] };

    const candidateFiles = [];
    if (Array.isArray(changedPaths) && changedPaths.length > 0) {
        for (const relPath of changedPaths) {
            if (!isBuildCheckable(relPath)) continue;
            const absPath = path.join(projectRoot, relPath.replace(/^\/+/, ''));
            if (fs.existsSync(absPath)) candidateFiles.push(absPath);
        }
    } else {
        // Scan ALL source files — not just entry points — so syntax errors in
        // pages / components are caught immediately (before the agent health-checks).
        const srcDir = path.join(projectRoot, 'src');
        if (fs.existsSync(srcDir)) {
            const walk = (dir) => {
                for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
                    if (entry.isDirectory()) {
                        walk(path.join(dir, entry.name));
                    } else if (/\.(tsx|jsx|ts|js)$/.test(entry.name)) {
                        candidateFiles.push(path.join(dir, entry.name));
                    }
                }
            };
            walk(srcDir);
        }
    }

    const errors = [];

    for (const absPath of candidateFiles) {
        try {
            const content = fs.readFileSync(absPath, 'utf-8');
            const ext = path.extname(absPath).toLowerCase();
            const { transformWithEsbuild } = await getViteApi();
            await transformWithEsbuild(content, absPath, {
                loader: ext === '.tsx' ? 'tsx' : ext === '.jsx' ? 'jsx' : ext === '.ts' ? 'ts' : 'js',
                jsx: 'automatic',
                sourcemap: false,
            });
        } catch (err) {
            const relPath = path.relative(projectRoot, absPath).replace(/\\/g, '/');
            if (Array.isArray(err?.errors) && err.errors.length > 0) {
                errors.push(...err.errors.map((e) => formatValidationError(relPath, e)));
            } else {
                errors.push(formatValidationError(relPath, err));
            }
        }
    }

    return { ok: errors.length === 0, errors };
}

function delimiterImbalanceScore(content) {
    const chars = String(content || '');
    let paren = 0;
    let brace = 0;
    let bracket = 0;

    for (let i = 0; i < chars.length; i++) {
        const ch = chars[i];
        if (ch === '(') paren += 1;
        else if (ch === ')') paren -= 1;
        else if (ch === '{') brace += 1;
        else if (ch === '}') brace -= 1;
        else if (ch === '[') bracket += 1;
        else if (ch === ']') bracket -= 1;
    }

    return Math.abs(paren) + Math.abs(brace) + Math.abs(bracket);
}

function trimTrailingOrphanClosers(content) {
    const lines = String(content || '').split(/\r?\n/);
    if (lines.length === 0) {
        return { content: String(content || ''), removed: 0 };
    }

    const orphanLinePattern = /^\s*[\)\}\];,]+\s*$/;
    let current = lines.slice();
    let currentScore = delimiterImbalanceScore(current.join('\n'));
    let removed = 0;

    while (current.length > 0 && orphanLinePattern.test(current[current.length - 1])) {
        const candidate = current.slice(0, -1);
        const candidateText = candidate.join('\n');
        const candidateScore = delimiterImbalanceScore(candidateText);
        if (candidateScore > currentScore) {
            break;
        }

        current = candidate;
        currentScore = candidateScore;
        removed += 1;
    }

    return { content: current.join('\n'), removed };
}

module.exports = {
    isBuildCheckable,
    getEsbuildLoader,
    formatValidationError,
    SKIP_VALIDATION_FILES,
    validateSourceFile,
    buildValidationResponse,
    repairMalformedDefaultStringParams,
    checkCrossFileImports,
    quickViteBuildCheck,
    delimiterImbalanceScore,
    trimTrailingOrphanClosers,
};
