// This file is automatically generated. Do not edit it directly.
//
// 2026-08 security audit note: the values below are a Supabase PUBLISHABLE
// (anon, role: "anon" per the JWT payload) key for a reference-only project,
// public by design -- not a server secret. This src/base-example/ tree is
// not referenced by vite.config.ts or tsconfig.json, so it is not compiled
// into the real app bundle. Left in place rather than scrubbed since this
// file is regenerated, not hand-maintained -- flag for removal if the source
// project (kjtahqmegagnaqajtfwi) is retired.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjtahqmegagnaqajtfwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdGFocW1lZ2FnbmFxYWp0ZndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NTI3ODksImV4cCI6MjA5MTMyODc4OX0.yQN6V8ZmpkZ-eMZMiyctIFy6iOapJ_kU2pJDnf542kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Pass-through lock, matching social-template. Every preview is served from
    // one origin, so GoTrue's default Navigator Lock (keyed off the Supabase
    // URL) is contended across every open preview tab of every project, not
    // just this one. A losing tab throws an uncaught
    // NavigatorLockAcquireTimeoutError during the init + visibility-change
    // auto-refresh race and can blank the page before it mounts. A preview does
    // not need cross-tab-synced refresh, so skip the lock.
    lock: (_name, _acquireTimeout, fn) => fn(),
  }
});