/**
 * GitHub connector — connect a GitHub account (OAuth), link a repo per project,
 * and push the project's current files to that repo as a single commit.
 */
import { Router, Request, Response } from 'express';
import { createHmac } from 'node:crypto';
import { authMiddleware, AuthenticatedRequest } from '../middleware/auth.middleware.js';
import { supabase, supabaseAuth } from '../config/database.js';
import { projectService } from '../services/project.service.js';
import { logger } from '../utils/logger.js';

const router = Router();

const GITHUB_CLIENT_ID     = process.env.GITHUB_CLIENT_ID || '';
const GITHUB_CLIENT_SECRET = process.env.GITHUB_CLIENT_SECRET || '';
const SERVER_URL = (process.env.ECOMGEAR_SERVER_URL || 'https://api.ecomgear.dev').replace(/\/$/, '');
const APP_URL    = (process.env.APP_URL || 'https://www.ecomgear.dev').replace(/\/$/, '');
// Must exactly match the "Authorization callback URL" registered on the
// GitHub OAuth App — that's /auth/github/callback, not /api/v1/github/callback.
const REDIRECT_URI = `${SERVER_URL}/auth/github/callback`;
// Reuses the tenant-DB HMAC secret purely as a signing key for this short-lived
// OAuth state token — no relation to tenant DB auth, just an existing secret.
const STATE_SECRET = process.env.TENANT_DB_JWT_SECRET || process.env.SUPABASE_JWT_SECRET || '';

function b64url(input: Buffer | string): string {
  return Buffer.from(input).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
}
function fromB64url(input: string): Buffer {
  return Buffer.from(input.replace(/-/g, '+').replace(/_/g, '/'), 'base64');
}

function signState(payload: { uid: string; pid?: string; exp: number }): string {
  const body = b64url(JSON.stringify(payload));
  const sig = b64url(createHmac('sha256', STATE_SECRET).update(body).digest());
  return `${body}.${sig}`;
}

function verifyState(state: string): { uid: string; pid?: string } | null {
  try {
    const [body, sig] = state.split('.');
    if (!body || !sig) return null;
    const expected = b64url(createHmac('sha256', STATE_SECRET).update(body).digest());
    if (sig !== expected) return null;
    const payload = JSON.parse(fromB64url(body).toString('utf8')) as { uid: string; pid?: string; exp: number };
    if (typeof payload.exp !== 'number' || payload.exp < Math.floor(Date.now() / 1000)) return null;
    if (typeof payload.uid !== 'string') return null;
    return { uid: payload.uid, pid: typeof payload.pid === 'string' ? payload.pid : undefined };
  } catch {
    return null;
  }
}

async function getConnection(userId: string) {
  const { data } = await supabase
    .from('github_connections')
    .select('access_token, github_login, avatar_url')
    .eq('user_id', userId)
    .maybeSingle();
  return data as { access_token: string; github_login: string; avatar_url: string | null } | null;
}

function ghHeaders(token: string) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  };
}

// Extracts GitHub's own error message from a failed response body, falling
// back to the raw status — "404" alone doesn't say whether the repo is
// missing, the token lacks scope, or something else.
async function ghErrorDetail(res: { json: () => Promise<any>; status: number }): Promise<string> {
  try {
    const body = await res.json() as { message?: string };
    return body.message ? `${res.status} ${body.message}` : String(res.status);
  } catch {
    return String(res.status);
  }
}

const ECOMGEAR_LOGO_URL = `${APP_URL}/favicon.ico`;

function buildEcomgearReadme(projectName: string): string {
  return `<p align="center">
  <img src="${ECOMGEAR_LOGO_URL}" alt="EcomGear" width="64" height="64" />
</p>

<h1 align="center">${projectName}</h1>

<p align="center">Built with <a href="${APP_URL}">EcomGear</a> — an AI app builder that generates full React web apps from a prompt.</p>

## About

This app was generated by EcomGear's AI agent and is kept in sync with this repository — every push from the editor lands here as a commit. To keep the two in sync, make changes through the EcomGear editor rather than editing this repo directly; direct edits here won't flow back into the project.

## Tech stack

- **React 18** + **TypeScript** + **Vite**
- **Tailwind CSS** with shadcn/ui components (Radix UI primitives)
- **React Router** for client-side routing
- **Supabase** client for auth/data, where used

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

The dev server starts on the port Vite prints in the terminal (typically \`http://localhost:5173\`).

### Build for production

\`\`\`bash
npm run build
npm run preview   # preview the production build locally
\`\`\`

The build output goes to \`dist/\` — deploy it to any static host (Vercel, Netlify, Cloudflare Pages, etc.), or continue using EcomGear's built-in publish flow.

## Project structure

\`\`\`
src/
  components/   Reusable UI components (including shadcn/ui primitives in src/components/ui/)
  pages/        Route-level page components
  lib/          Utilities (e.g. the cn() classname helper)
index.html      App entry HTML
vite.config.ts  Vite configuration
\`\`\`

## Deploying changes

Edit and generate through [EcomGear](${APP_URL}) — pushes land here automatically as commits, keeping this repo as a live mirror of the project.
`;
}

// Overwrites auto_init's default README.md with an EcomGear-branded one via
// the Contents API (requires the existing file's sha to update in place).
async function writeEcomgearReadme(accessToken: string, fullName: string, branch: string, projectName: string): Promise<void> {
  const headers = ghHeaders(accessToken);
  const getRes = await fetch(`https://api.github.com/repos/${fullName}/contents/README.md?ref=${branch}`, { headers });
  const sha = getRes.ok ? ((await getRes.json()) as { sha: string }).sha : undefined;

  const putRes = await fetch(`https://api.github.com/repos/${fullName}/contents/README.md`, {
    method: 'PUT',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      message: 'Initialize README — generated by EcomGear',
      content: Buffer.from(buildEcomgearReadme(projectName)).toString('base64'),
      branch,
      ...(sha ? { sha } : {}),
    }),
  });
  if (!putRes.ok) throw new Error(`Failed to write README: ${putRes.status}`);
}

// ── GET /api/v1/github/connect?token=<supabase_access_token> ─────────────────
// A top-level browser redirect, so it can't carry an Authorization header —
// the frontend passes the session token as a query param instead.
router.get('/connect', async (req: Request, res: Response) => {
  const token = req.query.token as string | undefined;
  const projectId = req.query.projectId as string | undefined;
  if (!token) { res.status(401).send('Missing token'); return; }
  if (!GITHUB_CLIENT_ID) { res.status(500).send('GitHub integration is not configured on this server.'); return; }

  const { data, error } = await supabaseAuth.auth.getUser(token);
  if (error || !data.user) { res.status(401).send('Invalid session'); return; }

  const state = signState({ uid: data.user.id, pid: projectId, exp: Math.floor(Date.now() / 1000) + 600 });
  const authorizeUrl = new URL('https://github.com/login/oauth/authorize');
  authorizeUrl.searchParams.set('client_id', GITHUB_CLIENT_ID);
  authorizeUrl.searchParams.set('redirect_uri', REDIRECT_URI);
  authorizeUrl.searchParams.set('scope', 'repo read:user');
  authorizeUrl.searchParams.set('state', state);
  res.redirect(authorizeUrl.toString());
});

// ── GET /api/v1/github/callback ───────────────────────────────────────────────
router.get('/callback', async (req: Request, res: Response) => {
  const code = req.query.code as string | undefined;
  const state = req.query.state as string | undefined;
  const verified = state ? verifyState(state) : null;
  const settingsUrl = verified?.pid
    ? `${APP_URL}/project/${verified.pid}/settings?section=project-integrations`
    : `${APP_URL}/dashboard/settings?section=project-integrations`;

  if (!code || !verified) {
    res.redirect(`${settingsUrl}&github=error`);
    return;
  }

  try {
    const tokenRes = await fetch('https://github.com/login/oauth/access_token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({
        client_id: GITHUB_CLIENT_ID,
        client_secret: GITHUB_CLIENT_SECRET,
        code,
        redirect_uri: REDIRECT_URI,
      }),
    });
    const tokenJson = await tokenRes.json() as { access_token?: string; scope?: string; error?: string };
    if (!tokenJson.access_token) {
      logger.warn('[GitHub OAuth] token exchange failed', { error: tokenJson.error });
      res.redirect(`${settingsUrl}&github=error`);
      return;
    }

    const userRes = await fetch('https://api.github.com/user', { headers: ghHeaders(tokenJson.access_token) });
    const ghUser = await userRes.json() as { id: number; login: string; avatar_url: string };
    if (!userRes.ok || !ghUser.id) {
      res.redirect(`${settingsUrl}&github=error`);
      return;
    }

    await supabase.from('github_connections').upsert(
      {
        user_id: verified.uid,
        github_user_id: ghUser.id,
        github_login: ghUser.login,
        avatar_url: ghUser.avatar_url,
        access_token: tokenJson.access_token,
        scope: tokenJson.scope ?? null,
        connected_at: new Date().toISOString(),
      },
      { onConflict: 'user_id' }
    );

    res.redirect(`${settingsUrl}&github=connected`);
  } catch (err) {
    logger.error('[GitHub OAuth] callback error', err);
    res.redirect(`${settingsUrl}&github=error`);
  }
});

// ── GET /api/v1/github/status ──────────────────────────────────────────────
router.get('/status', authMiddleware, async (req: AuthenticatedRequest, res: Response) => {
  const conn = await getConnection(req.user!.id);
  res.json(conn
    ? { connected: true, login: conn.github_login, avatarUrl: conn.avatar_url }
    : { connected: false });
});

// ── DELETE /api/v1/github/disconnect ───────────────────────────────────────
router.delete('/disconnect', authMiddleware, async (req: AuthenticatedRequest, res: Response) => {
  const conn = await getConnection(req.user!.id);
  if (conn && GITHUB_CLIENT_ID && GITHUB_CLIENT_SECRET) {
    // Best-effort revoke on GitHub's side too — non-fatal if it fails.
    fetch(`https://api.github.com/applications/${GITHUB_CLIENT_ID}/grant`, {
      method: 'DELETE',
      headers: {
        Authorization: `Basic ${Buffer.from(`${GITHUB_CLIENT_ID}:${GITHUB_CLIENT_SECRET}`).toString('base64')}`,
        Accept: 'application/vnd.github+json',
      },
      body: JSON.stringify({ access_token: conn.access_token }),
    }).catch(() => {});
  }
  await supabase.from('github_connections').delete().eq('user_id', req.user!.id);
  res.json({ success: true });
});

// ── GET /api/v1/github/:projectId/link ──────────────────────────────────────
// Note: there is deliberately no endpoint to list or link an arbitrary
// existing repo — the connected token can technically reach the whole
// account (GitHub OAuth Apps can't scope by repo), but this app only ever
// creates and touches the one repo it made for each project.
router.get('/:projectId/link', authMiddleware, async (req: AuthenticatedRequest, res: Response) => {
  try {
    await projectService.getProject(req.params.projectId, req.user!.id);
  } catch {
    res.status(404).json({ error: 'Project not found or access denied.' });
    return;
  }
  const { data } = await supabase
    .from('project_settings')
    .select('setting_value')
    .eq('project_id', req.params.projectId)
    .eq('setting_key', 'github_repo')
    .maybeSingle();
  res.json({ link: data?.setting_value ?? null });
});

// ── POST /api/v1/github/:projectId/create-repo ───────────────────────────────
// Creates a brand-new repo on the connected GitHub account and links this
// project to it in one step (for users with no existing repo to push to).
router.post('/:projectId/create-repo', authMiddleware, async (req: AuthenticatedRequest, res: Response) => {
  const { name, private: isPrivate, description } = req.body as { name?: string; private?: boolean; description?: string };
  if (!name || !/^[\w.-]+$/.test(name)) { res.status(400).json({ error: 'name must contain only letters, numbers, "-", "_", "."' }); return; }

  let project: any;
  try {
    project = await projectService.getProject(req.params.projectId, req.user!.id);
  } catch {
    res.status(404).json({ error: 'Project not found or access denied.' });
    return;
  }

  const conn = await getConnection(req.user!.id);
  if (!conn) { res.status(403).json({ error: 'GitHub account not connected.' }); return; }

  try {
    const r = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: { ...ghHeaders(conn.access_token), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name,
        private: isPrivate ?? true,
        description: description || `${project?.name ?? name} — built with EcomGear`,
        auto_init: true,
      }),
    });
    const body = await r.json() as { full_name?: string; default_branch?: string; html_url?: string; message?: string };
    if (!r.ok) { res.status(r.status).json({ error: body.message ?? `GitHub API error: ${r.status}` }); return; }

    const link = { fullName: body.full_name!, branch: body.default_branch || 'main' };
    await supabase.from('project_settings').upsert(
      {
        project_id: req.params.projectId,
        setting_key: 'github_repo',
        setting_value: link,
        updated_at: new Date().toISOString(),
      },
      { onConflict: 'project_id,setting_key' }
    );

    // Best-effort: replace auto_init's default README with an EcomGear-branded
    // one. Non-fatal — repo creation already succeeded even if this fails.
    await writeEcomgearReadme(conn.access_token, link.fullName, link.branch, project?.name ?? name).catch(
      (err) => logger.warn('[GitHub create-repo] README write failed', err)
    );

    res.json({ ...link, htmlUrl: body.html_url });
  } catch (err) {
    res.status(500).json({ error: (err as Error).message });
  }
});

// ── POST /api/v1/github/:projectId/push ─────────────────────────────────────
// Pushes the project's current files as a single commit to the linked repo/branch.
export interface PushToGithubResult {
  success: boolean;
  filesPushed?: number;
  commitUrl?: string;
  error?: string;
  /** HTTP-style status for route callers; agent-tool callers can ignore it. */
  status?: number;
}

/**
 * Core push logic: one commit (blob → tree → commit → ref update) to the
 * repo linked to this project. Shared by the /push route (browser-driven,
 * files from the client's resolved revision) and the push_to_github agent
 * tool (files read straight off disk mid-run).
 */
export async function pushFilesToGithub(
  userId: string,
  projectId: string,
  files: { path: string; content: string; encoding?: 'base64' }[],
): Promise<PushToGithubResult> {
  if (files.length === 0) return { success: false, error: 'No files provided to push.', status: 400 };

  try {
    await projectService.getProject(projectId, userId);
  } catch {
    return { success: false, error: 'Project not found or access denied.', status: 404 };
  }

  const conn = await getConnection(userId);
  if (!conn) return { success: false, error: 'GitHub account not connected.', status: 403 };

  const { data: linkRow } = await supabase
    .from('project_settings')
    .select('setting_value')
    .eq('project_id', projectId)
    .eq('setting_key', 'github_repo')
    .maybeSingle();
  const link = linkRow?.setting_value as { fullName?: string; branch?: string } | undefined;
  if (!link?.fullName) return { success: false, error: 'No GitHub repo linked to this project yet.', status: 400 };

  const [owner, repo] = link.fullName.split('/');
  const branch = link.branch || 'main';
  const headers = ghHeaders(conn.access_token);

  try {
    // Preflight: confirm the linked repo still exists before doing any blob
    // work — a clearer failure than a mid-push 404, and self-heals a stale
    // link (e.g. the repo was deleted on GitHub after linking).
    const repoCheckRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
    if (!repoCheckRes.ok) {
      if (repoCheckRes.status === 404) {
        await supabase.from('project_settings').delete()
          .eq('project_id', projectId).eq('setting_key', 'github_repo');
        return { success: false, error: `Repository ${link.fullName} no longer exists on GitHub — create a new one.`, status: 404 };
      }
      return { success: false, error: `Could not access ${link.fullName} on GitHub (${repoCheckRes.status}).`, status: repoCheckRes.status };
    }

    // Resolve current branch tip (may not exist yet on an empty repo).
    let baseCommitSha: string | undefined;
    const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${branch}`, { headers });
    if (refRes.ok) {
      const refJson = await refRes.json() as { object: { sha: string } };
      baseCommitSha = refJson.object.sha;
    }

    let baseTreeSha: string | undefined;
    if (baseCommitSha) {
      const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits/${baseCommitSha}`, { headers });
      if (commitRes.ok) baseTreeSha = ((await commitRes.json()) as { tree: { sha: string } }).tree.sha;
    }

    // Create a blob per file, then one tree, one commit, one ref update — an
    // atomic single commit instead of one commit per file.
    const treeEntries = [];
    for (const f of files) {
      const base64Content = f.encoding === 'base64' ? f.content : Buffer.from(f.content, 'utf8').toString('base64');
      const blobRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/blobs`, {
        method: 'POST', headers,
        body: JSON.stringify({ content: base64Content, encoding: 'base64' }),
      });
      if (!blobRes.ok) throw new Error(`Failed to create blob for ${f.path}: ${await ghErrorDetail(blobRes)}`);
      const blob = await blobRes.json() as { sha: string };
      treeEntries.push({ path: f.path, mode: '100644', type: 'blob', sha: blob.sha });
    }

    const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, {
      method: 'POST', headers,
      body: JSON.stringify({ base_tree: baseTreeSha, tree: treeEntries }),
    });
    if (!treeRes.ok) throw new Error(`Failed to create tree: ${await ghErrorDetail(treeRes)}`);
    const tree = await treeRes.json() as { sha: string };

    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, {
      method: 'POST', headers,
      body: JSON.stringify({
        message: `Sync from EcomGear — ${new Date().toISOString()}`,
        tree: tree.sha,
        parents: baseCommitSha ? [baseCommitSha] : [],
      }),
    });
    if (!commitRes.ok) throw new Error(`Failed to create commit: ${await ghErrorDetail(commitRes)}`);
    const commit = await commitRes.json() as { sha: string };

    const updateRefRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
      method: baseCommitSha ? 'PATCH' : 'POST',
      headers,
      body: JSON.stringify(
        baseCommitSha
          ? { sha: commit.sha, force: false }
          : { ref: `refs/heads/${branch}`, sha: commit.sha }
      ),
    });
    if (!updateRefRes.ok) throw new Error(`Failed to update ref: ${await ghErrorDetail(updateRefRes)}`);

    return { success: true, filesPushed: files.length, commitUrl: `https://github.com/${owner}/${repo}/commit/${commit.sha}` };
  } catch (err) {
    logger.error('[GitHub push] error', err);
    return { success: false, error: (err as Error).message, status: 500 };
  }
}

router.post('/:projectId/push', authMiddleware, async (req: AuthenticatedRequest, res: Response) => {
  const { projectId } = req.params;
  // Files come from the client, which already has the current revision's
  // full file set resolved (via revisionService.getRevisionFilesForExport) —
  // the project's real content lives in Supabase Storage / the revisions
  // table, not on this server's local disk, so there's nothing to walk here.
  const files = req.body?.files as { path: string; content: string; encoding?: 'base64' }[] | undefined;
  if (!files || files.length === 0) { res.status(400).json({ error: 'No files provided to push.' }); return; }

  const result = await pushFilesToGithub(req.user!.id, projectId, files);
  res.status(result.success ? 200 : (result.status ?? 500)).json(result);
});

export default router;
