// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjtahqmegagnaqajtfwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdGFocW1lZ2FnbmFxYWp0ZndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NTI3ODksImV4cCI6MjA5MTMyODc4OX0.yQN6V8ZmpkZ-eMZMiyctIFy6iOapJ_kU2pJDnf542kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});