import { registerAppHandlers } from "./handlers/app_handlers.js";
import { registerChatHandlers } from "./handlers/chat_handlers.js";
import { registerChatStreamHandlers } from "./handlers/chat_stream_handlers.js";
import { registerSettingsHandlers } from "./handlers/settings_handlers.js";
import { registerShellHandlers } from "./handlers/shell_handler.js";
import { registerDependencyHandlers } from "./handlers/dependency_handlers.js";
import { registerCustomAppsFolderHandlers } from "./handlers/custom_apps_folder_handlers.js";
import { registerGithubHandlers } from "./handlers/github_handlers.js";
import { registerGithubBranchHandlers } from "./handlers/git_branch_handlers.js";
import { registerVercelHandlers } from "./handlers/vercel_handlers.js";
import { registerNodeHandlers } from "./handlers/node_handlers.js";
import { registerProposalHandlers } from "./handlers/proposal_handlers.js";
import { registerDebugHandlers } from "./handlers/debug_handlers.js";
import { registerSupabaseHandlers } from "./handlers/supabase_handlers.js";
import { registerNeonHandlers } from "./handlers/neon_handlers.js";
import { registerLocalModelHandlers } from "./handlers/local_model_handlers.js";
import { registerTokenCountHandlers } from "./handlers/token_count_handlers.js";
import { registerWindowHandlers } from "./handlers/window_handlers.js";
import { registerUploadHandlers } from "./handlers/upload_handlers.js";
import { registerVersionHandlers } from "./handlers/version_handlers.js";
import { registerLanguageModelHandlers } from "./handlers/language_model_handlers.js";
import { registerReleaseNoteHandlers } from "./handlers/release_note_handlers.js";
import { registerImportHandlers } from "./handlers/import_handlers.js";
import { registerSessionHandlers } from "./handlers/session_handlers.js";
import { registerProHandlers } from "./handlers/pro_handlers.js";
import { registerContextPathsHandlers } from "./handlers/context_paths_handlers.js";
import { registerAppUpgradeHandlers } from "./handlers/app_upgrade_handlers.js";
import { registerCapacitorHandlers } from "./handlers/capacitor_handlers.js";
import { registerProblemsHandlers } from "./handlers/problems_handlers.js";
import { registerAppEnvVarsHandlers } from "./handlers/app_env_vars_handlers.js";
import { registerTemplateHandlers } from "./handlers/template_handlers.js";
import { registerThemesHandlers } from "../pro/main/ipc/handlers/themes_handlers.js";
import { registerPortalHandlers } from "./handlers/portal_handlers.js";
import { registerPromptHandlers } from "./handlers/prompt_handlers.js";
import { registerHelpBotHandlers } from "./handlers/help_bot_handlers.js";
import { registerMcpHandlers } from "./handlers/mcp_handlers.js";
import { registerSecurityHandlers } from "./handlers/security_handlers.js";
import { registerVisualEditingHandlers } from "../pro/main/ipc/handlers/visual_editing_handlers.js";
import { registerAgentToolHandlers } from "../pro/main/ipc/handlers/local_agent/agent_tool_handlers.js";
import { registerFreeAgentQuotaHandlers } from "./handlers/free_agent_quota_handlers.js";
import { registerPlanHandlers } from "./handlers/plan_handlers.js";
import { registerMediaHandlers } from "./handlers/media_handlers.js";
import { registerImageGenerationHandlers } from "./handlers/image_generation_handlers.js";

export function registerIpcHandlers() {
  // Register all IPC handlers by category
  registerAppHandlers();
  registerChatHandlers();
  registerChatStreamHandlers();
  registerSettingsHandlers();
  registerShellHandlers();
  registerDependencyHandlers();
  registerCustomAppsFolderHandlers();
  registerGithubHandlers();
  registerGithubBranchHandlers();
  registerVercelHandlers();
  registerNodeHandlers();
  registerProblemsHandlers();
  registerProposalHandlers();
  registerDebugHandlers();
  registerSupabaseHandlers();
  registerNeonHandlers();
  registerLocalModelHandlers();
  registerTokenCountHandlers();
  registerWindowHandlers();
  registerUploadHandlers();
  registerVersionHandlers();
  registerLanguageModelHandlers();
  registerReleaseNoteHandlers();
  registerImportHandlers();
  registerSessionHandlers();
  registerProHandlers();
  registerContextPathsHandlers();
  registerAppUpgradeHandlers();
  registerCapacitorHandlers();
  registerAppEnvVarsHandlers();
  registerTemplateHandlers();
  registerThemesHandlers();
  registerPortalHandlers();
  registerPromptHandlers();
  registerHelpBotHandlers();
  registerMcpHandlers();
  registerSecurityHandlers();
  registerVisualEditingHandlers();
  registerAgentToolHandlers();
  registerFreeAgentQuotaHandlers();
  registerPlanHandlers();
  registerMediaHandlers();
  registerImageGenerationHandlers();
}
