import { supabase } from '../config/database.js';
import { createHash } from 'node:crypto';

// The one-time launch-token handoff from agent-portal's "Dashboard Creator"
// (a POST / route here, exchanging a token with app-builder.ts's /verify +
// /complete) is retired   both the portal's trigger page and its backend
// endpoints are gone (agent-portal's AppBuilderPage/app-builder.ts, removed
// 2026-07-23). Onboarding now goes through ecg-dev-agent.routes.ts (paste an
// MCP API key, no portal token exchange). This module (no longer a router)
// now only exports the two shared file-sync helpers below   ecg-dev-agent.
// routes.ts and ecg-customize.routes.ts both depend on them.

// ── Shared file-sync helpers ─────────────────────────────────────────────────
// Extracted from the connect handler above so the Customizer's re-bake (a
// separate endpoint below) can push edited files through the exact same path
// -- storage + revision manifest, then a preview-service overlay push -- instead
// of duplicating either half.

/**
 * Store files in Supabase revisions so the SMEsAgent editor can read them.
 * Files go to Storage + a lean manifest row, never inline in generated_files
 * -- that used to hold raw file content directly, which silently re-inflated a
 * project's revision to tens of MB every time this ran (confirmed on CardPro,
 * 2026-07-22: 163 then 177 files, 19MB+ inline, same manifest-format fix
 * applied to revisionService.ts).
 */
export async function saveEcgRevision(
  projectId: string,
  userId: string,
  filesArray: { path: string; content: string }[],
  summary: string,
): Promise<void> {
  const { data: existingRev } = await supabase
    .from('revisions')
    .select('id')
    .eq('project_id', projectId)
    .order('revision_number', { ascending: false })
    .limit(1)
    .maybeSingle();

  let revisionId = existingRev?.id as string | undefined;
  if (!revisionId) {
    const { data: inserted, error: insertErr } = await supabase
      .from('revisions')
      .insert({
        project_id: projectId,
        user_id: userId,
        revision_number: 1,
        prompt: 'eCG dashboard   generated by App Builder',
        generated_code: filesArray.map(f => `// ${f.path}\n${f.content}`).join('\n\n---\n\n'),
        preview_status: 'pending' as const,
        is_published: false,
      })
      .select('id')
      .single();
    if (insertErr || !inserted) throw insertErr ?? new Error('Failed to create revision');
    revisionId = inserted.id;
  }

  const manifestFiles: { path: string; hash: string; source_revision: string }[] = [];
  const uploadErrors: string[] = [];
  const UPLOAD_BATCH_SIZE = 5;
  for (let i = 0; i < filesArray.length; i += UPLOAD_BATCH_SIZE) {
    const batch = filesArray.slice(i, i + UPLOAD_BATCH_SIZE);
    await Promise.all(batch.map(async (f) => {
      const hash = createHash('sha256').update(f.content, 'utf8').digest('hex');
      const storagePath = `projects/${projectId}/${revisionId}/${f.path}`;
      const { error: upErr } = await supabase.storage
        .from('user-projects-free')
        .upload(storagePath, Buffer.from(f.content, 'utf8'), { contentType: 'text/plain', upsert: true });
      if (upErr) { uploadErrors.push(`${f.path}: ${upErr.message}`); return; }
      manifestFiles.push({ path: f.path, hash, source_revision: revisionId! });
    }));
  }
  if (uploadErrors.length > 0) {
    throw new Error(`eCG dashboard file upload failed: ${uploadErrors.join('; ')}`);
  }

  await supabase.from('revisions').update({
    generated_files: { format: 'manifest-v1', files: manifestFiles, summary },
    file_count: manifestFiles.length,
    preview_status: 'pending' as const,
  }).eq('id', revisionId);
}

/**
 * Push template files to the preview service (VPS2) so the live preview works.
 * fullSync must be false: this is an OVERLAY onto the base scaffold
 * initProjectFromTemplate() writes (package.json, vite.config.ts, tsconfig*.json,
 * node_modules)   agent-template/ never includes those files, so a fullSync
 * prune deletes them immediately, breaking the build. This was silently
 * corrupting every fresh Dashboard Creator launch before the fix.
 */
export async function syncEcgPreviewService(
  projectId: string,
  filesArray: { path: string; content: string }[],
): Promise<void> {
  const previewServiceUrl = process.env.PREVIEW_SERVICE_URL || 'https://preview.SMEsAgent.app';
  const previewSecret = process.env.PREVIEW_UPDATE_SECRET || '';
  try {
    await fetch(`${previewServiceUrl}/preview/${projectId}/update`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-update-secret': previewSecret },
      body: JSON.stringify({ files: filesArray, fullSync: false }),
    });
  } catch { /* preview push is non-fatal */ }
}
