// Reads the agent-template folder and injects it as a Supabase-ready file map.
// Only ecg-config.ts is generated dynamically; all other files are read verbatim
// (with {{CSS_VARS}} and {{APP_NAME}} substituted).

import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = path.resolve(__dirname, '../../agent-template');

export interface TemplateOptions {
  orgName: string;
  modules: string[];
  agentIds: string[];
  config: Record<string, unknown>;
  projectId: string;
  proxyUrl: string;
}

interface DesignCfg {
  appName: string;
  layout: 'sidebar' | 'topnav' | 'minimal';
  theme: string;
  accentColor: string;
  sidebarColor: string;
  bodyColor: string;
  showSummaryCards: boolean;
  moduleSettings: Record<string, Record<string, boolean | string>>;
}

const THEME_DEFAULTS: Record<string, Pick<DesignCfg, 'accentColor' | 'sidebarColor' | 'bodyColor'>> = {
  light:  { accentColor: '#2563eb', sidebarColor: '#ffffff', bodyColor: '#f8fafc' },
  dark:   { accentColor: '#60a5fa', sidebarColor: '#0f172a', bodyColor: '#020617' },
  ocean:  { accentColor: '#00b4d8', sidebarColor: '#0f4c75', bodyColor: '#f0f9ff' },
  forest: { accentColor: '#22c55e', sidebarColor: '#1a3a2a', bodyColor: '#f0fdf4' },
  sunset: { accentColor: '#f97316', sidebarColor: '#7c2d12', bodyColor: '#fff7ed' },
  slate:  { accentColor: '#8b5cf6', sidebarColor: '#334155', bodyColor: '#f8fafc' },
};

function resolveDesign(raw: Record<string, unknown>, orgName: string): DesignCfg {
  const themeKey = (raw.theme as string) || 'light';
  const def = THEME_DEFAULTS[themeKey] ?? THEME_DEFAULTS.light;
  return {
    appName:         (raw.appName as string) || orgName,
    layout:          (raw.layout as DesignCfg['layout']) || 'sidebar',
    theme:           themeKey,
    accentColor:     (raw.accentColor as string) || def.accentColor,
    sidebarColor:    (raw.sidebarColor as string) || def.sidebarColor,
    bodyColor:       (raw.bodyColor as string) || def.bodyColor,
    showSummaryCards: (raw.showSummaryCards as boolean) !== false,
    moduleSettings:  (raw.moduleSettings as DesignCfg['moduleSettings']) || {},
  };
}

function isDark(hex: string): boolean {
  const c = hex.replace('#', '');
  const r = parseInt(c.slice(0, 2), 16);
  const g = parseInt(c.slice(2, 4), 16);
  const b = parseInt(c.slice(4, 6), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 < 128;
}

function cssVars(d: DesignCfg): string {
  const sidebarText  = isDark(d.sidebarColor) ? '#f1f5f9' : '#1e293b';
  const sidebarMuted = isDark(d.sidebarColor) ? '#94a3b8' : '#64748b';
  const accentBg     = `${d.accentColor}1a`;
  const cardBg       = isDark(d.bodyColor) ? '#1e293b' : '#ffffff';
  const border       = isDark(d.bodyColor) ? '#334155' : '#e2e8f0';
  const text         = isDark(d.bodyColor) ? '#f1f5f9' : '#1e293b';
  const muted        = isDark(d.bodyColor) ? '#94a3b8' : '#64748b';
  return `:root {
  --accent: ${d.accentColor};
  --accent-bg: ${accentBg};
  --sidebar-bg: ${d.sidebarColor};
  --sidebar-text: ${sidebarText};
  --sidebar-muted: ${sidebarMuted};
  --body-bg: ${d.bodyColor};
  --card-bg: ${cardBg};
  --border: ${border};
  --text: ${text};
  --muted: ${muted};
}`;
}

function ecgConfigTs(d: DesignCfg, modules: string[], projectId: string, proxyUrl: string): string {
  const ALL_MODULES = ['agents', 'schedulers', 'posts', 'connectors', 'runs', 'knowledge'];
  const mods = modules.length > 0 ? modules : ALL_MODULES;
  return `// Auto-generated by App Builder — do not edit manually.
export const ECG = {
  appName: ${JSON.stringify(d.appName)},
  layout: ${JSON.stringify(d.layout)} as 'sidebar' | 'topnav' | 'minimal',
  modules: ${JSON.stringify(mods)} as string[],
  showSummaryCards: ${d.showSummaryCards},
  accentColor: ${JSON.stringify(d.accentColor)},
  proxyUrl: ${JSON.stringify(proxyUrl)},
  projectId: ${JSON.stringify(projectId)},
};
`;
}

/** Read all files from agent-template/, substitute placeholders, return file map. */
export function seedEcgTemplate(
  projectDir: string,
  opts: TemplateOptions,
): Record<string, string> {
  const design = resolveDesign(opts.config, opts.orgName);
  const vars   = cssVars(design);
  const files: Record<string, string> = {};

  // Walk template directory
  function walk(dir: string) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) { walk(full); continue; }
      const rel  = path.relative(TEMPLATE_DIR, full);
      let content = fs.readFileSync(full, 'utf8');
      // Substitute placeholders
      content = content.replace('{{CSS_VARS}}', vars);
      content = content.replace('{{APP_NAME}}', design.appName);
      files[rel] = content;
    }
  }

  try {
    walk(TEMPLATE_DIR);
  } catch (e) {
    // Template dir missing in dev — emit minimal stub
    files['src/ecg-config.ts'] = ecgConfigTs(design, opts.modules, opts.projectId, opts.proxyUrl);
    return files;
  }

  // Inject the generated config (overrides any placeholder in template)
  files['src/ecg-config.ts'] = ecgConfigTs(design, opts.modules, opts.projectId, opts.proxyUrl);

  // Write to disk (VPS3 local path) — non-fatal
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(projectDir, rel);
    try {
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, content, 'utf8');
    } catch { /* non-fatal */ }
  }

  return files;
}
