// Reads the agent-template folder and injects it as a Supabase-ready file map.
// Only ecg-config.ts is generated dynamically; all other files are read verbatim
// (with {{CSS_VARS}} and {{APP_NAME}} substituted).

import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = path.resolve(__dirname, '../../agent-template');

export interface TemplateOptions {
  orgName: string;
  modules: string[];
  agentIds: string[];
  config: Record<string, unknown>;
  projectId: string;
  proxyUrl: string;
}

interface DesignCfg {
  appName: string;
  logoUrl: string;
  layout: 'sidebar' | 'topnav' | 'minimal';
  theme: string;
  accentColor: string;
  sidebarColor: string;
  bodyColor: string;
  fontFamily: string;
  showSummaryCards: boolean;
  moduleSettings: Record<string, Record<string, boolean | string>>;
}

// Sidebar is a solid, saturated surface, not a near-white panel that blends
// into the body   this single choice is the biggest lever on whether a
// generated dashboard reads as "a real product" vs. a generic admin scaffold.
const THEME_DEFAULTS: Record<string, Pick<DesignCfg, 'accentColor' | 'sidebarColor' | 'bodyColor'>> = {
  light:  { accentColor: '#2563eb', sidebarColor: '#161c3d', bodyColor: '#f4f5f7' },
  dark:   { accentColor: '#60a5fa', sidebarColor: '#111827', bodyColor: '#030712' },
  ocean:  { accentColor: '#0ea5c9', sidebarColor: '#0c3d5e', bodyColor: '#eef8fc' },
  forest: { accentColor: '#16a34a', sidebarColor: '#16301f', bodyColor: '#eef8f0' },
  sunset: { accentColor: '#ea580c', sidebarColor: '#6b2810', bodyColor: '#fef3ea' },
  slate:  { accentColor: '#7c3aed', sidebarColor: '#293548', bodyColor: '#f4f5f7' },
};

function resolveDesign(raw: Record<string, unknown>, orgName: string): DesignCfg {
  const themeKey = (raw.theme as string) || 'light';
  const def = THEME_DEFAULTS[themeKey] ?? THEME_DEFAULTS.light;
  return {
    appName:         (raw.appName as string) || orgName,
    logoUrl:         (raw.logoUrl as string) || '',
    layout:          (raw.layout as DesignCfg['layout']) || 'sidebar',
    theme:           themeKey,
    accentColor:     (raw.accentColor as string) || def.accentColor,
    sidebarColor:    (raw.sidebarColor as string) || def.sidebarColor,
    bodyColor:       (raw.bodyColor as string) || def.bodyColor,
    fontFamily:      (raw.fontFamily as string) || 'Inter',
    showSummaryCards: (raw.showSummaryCards as boolean) !== false,
    moduleSettings:  (raw.moduleSettings as DesignCfg['moduleSettings']) || {},
  };
}

function isDark(hex: string): boolean {
  const c = hex.replace('#', '');
  const r = parseInt(c.slice(0, 2), 16);
  const g = parseInt(c.slice(2, 4), 16);
  const b = parseInt(c.slice(4, 6), 16);
  return (r * 299 + g * 587 + b * 114) / 1000 < 128;
}

// Shifts a hex color darker (positive amount) or lighter (negative), clamped to 0-255.
function shade(hex: string, amount: number): string {
  const c = hex.replace('#', '');
  const clamp = (n: number) => Math.max(0, Math.min(255, n));
  const r = clamp(parseInt(c.slice(0, 2), 16) - amount);
  const g = clamp(parseInt(c.slice(2, 4), 16) - amount);
  const b = clamp(parseInt(c.slice(4, 6), 16) - amount);
  return `#${[r, g, b].map(n => n.toString(16).padStart(2, '0')).join('')}`;
}

function cssVars(d: DesignCfg): string {
  const sidebarText  = isDark(d.sidebarColor) ? '#f1f5f9' : '#1e293b';
  const sidebarMuted = isDark(d.sidebarColor) ? '#94a3b8' : '#64748b';
  const accentBg     = `${d.accentColor}1a`;
  const accentHover  = shade(d.accentColor, isDark(d.bodyColor) ? -20 : 20);
  const sidebarHover = shade(d.sidebarColor, isDark(d.sidebarColor) ? -12 : 12);
  const cardBg       = isDark(d.bodyColor) ? '#1e293b' : '#ffffff';
  const inputBg      = isDark(d.bodyColor) ? '#0f172a' : '#ffffff';
  const border       = isDark(d.bodyColor) ? '#334155' : '#e2e8f0';
  const text         = isDark(d.bodyColor) ? '#f1f5f9' : '#1e293b';
  const muted        = isDark(d.bodyColor) ? '#94a3b8' : '#64748b';
  return `:root {
  --accent: ${d.accentColor};
  --accent-bg: ${accentBg};
  --accent-hover: ${accentHover};
  --sidebar-bg: ${d.sidebarColor};
  --sidebar-text: ${sidebarText};
  --sidebar-muted: ${sidebarMuted};
  --sidebar-hover: ${sidebarHover};
  --body-bg: ${d.bodyColor};
  --card-bg: ${cardBg};
  --input-bg: ${inputBg};
  --border: ${border};
  --text: ${text};
  --muted: ${muted};
  --radius: 12px;
  --radius-sm: 8px;
  --shadow-sm: 0 1px 2px rgba(15, 23, 42, 0.04);
  --shadow-md: 0 1px 2px rgba(15, 23, 42, 0.04), 0 12px 24px -12px rgba(15, 23, 42, 0.16);
  --font-weight-heading: 600;
}`;
}

function ecgConfigTs(d: DesignCfg, modules: string[], projectId: string, proxyUrl: string): string {
  const ALL_MODULES = ['agents', 'schedulers', 'posts', 'connectors', 'runs', 'knowledge'];
  const mods = modules.length > 0 ? modules : ALL_MODULES;
  return `// Auto-generated by App Builder   do not edit manually.
export const ECG = {
  appName: ${JSON.stringify(d.appName)},
  logoUrl: ${JSON.stringify(d.logoUrl)},
  layout: ${JSON.stringify(d.layout)} as 'sidebar' | 'topnav' | 'minimal',
  modules: ${JSON.stringify(mods)} as string[],
  showSummaryCards: ${d.showSummaryCards},
  accentColor: ${JSON.stringify(d.accentColor)},
  fontFamily: ${JSON.stringify(d.fontFamily)},
  proxyUrl: ${JSON.stringify(proxyUrl)},
  projectId: ${JSON.stringify(projectId)},
  moduleSettings: ${JSON.stringify(d.moduleSettings)} as Record<string, Record<string, boolean | string>>,
};
`;
}

/** Read all files from agent-template/, substitute placeholders, return file map. */
export function seedEcgTemplate(
  projectDir: string,
  opts: TemplateOptions,
): Record<string, string> {
  const design = resolveDesign(opts.config, opts.orgName);
  const vars   = cssVars(design);
  const files: Record<string, string> = {};

  // Walk template directory
  function walk(dir: string) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) { walk(full); continue; }
      const rel  = path.relative(TEMPLATE_DIR, full);
      let content = fs.readFileSync(full, 'utf8');
      // Substitute placeholders
      content = content.replace('{{CSS_VARS}}', vars);
      content = content.replace('{{APP_NAME}}', design.appName);
      content = content.replace('{{FONT_FAMILY}}', design.fontFamily);
      content = content.replace('{{FONT_FAMILY_URL}}', design.fontFamily.replace(/ /g, '+'));
      content = content.replace('{{LOGO_URL}}', design.logoUrl);
      files[rel] = content;
    }
  }

  try {
    walk(TEMPLATE_DIR);
  } catch (e) {
    // Template dir missing in dev   emit minimal stub
    files['src/ecg-config.ts'] = ecgConfigTs(design, opts.modules, opts.projectId, opts.proxyUrl);
    return files;
  }

  // Inject the generated config (overrides any placeholder in template)
  files['src/ecg-config.ts'] = ecgConfigTs(design, opts.modules, opts.projectId, opts.proxyUrl);

  // Write to disk (VPS3 local path)   non-fatal
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(projectDir, rel);
    try {
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, content, 'utf8');
    } catch { /* non-fatal */ }
  }

  return files;
}
