ALTER TABLE usage_tracking ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE usage_tracking ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE usage_tracking ADD COLUMN IF NOT EXISTS project_id UUID REFERENCES projects(id) ON DELETE SET NULL;
